export type Predicate = (...args: any[]) => boolean

export * from "./attempt/attempt"
export * from "./bindAll/bindAll"
export * from "./classNames/classNames"
export * from "./debounce/debounce"
export * from "./decodeHTMLEntities/decodeHTMLEntities"
export * from "./every/every"
export * from "./filter/filter"
export * from "./forEach/forEach"
export * from "./get/get"
export * from "./identity/identity"
export * from "./map/map"
export * from "./mapKeys/mapKeys"
export * from "./memoize/memoize"
export * from "./noop/noop"
export * from "./promisify/promisify"
export * from "./reduce/reduce"
export * from "./set/set"
export * from "./some/some"
export * from "./times/times"
export * from "./typeGuards/typeGuards"
